name: Model Training Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'src/model/**'
      - 'Data/final/**'
  workflow_dispatch:

env:
  PROJECT_ID: estateiqclone
  REGION: us-central1
  ARTIFACT_REGISTRY: estateiq-models
  MODEL_PATH: models/estate_price_prediction
  SA_EMAIL: self-522@estateiqclone.iam.gserviceaccount.com
  SERVICE_NAME: estateiq-prediction
  # Add substitution values that match cloudbuild.yaml
  GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
  NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
  MLFLOW_TRACKING_URI: sqlite:///mlflow.db

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc[gs] google-cloud-storage

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        service_account: ${{ env.SA_EMAIL }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2


    - name: Deploy to Cloud Run
      run: |
        # Make script executable
        chmod +x scripts/start_service.sh
        
        # Deploy using start_service.sh
        ./scripts/start_service.sh \
          --project-id ${{ env.PROJECT_ID }} \
          --region ${{ env.REGION }} \
          --service-name ${{ env.SERVICE_NAME }} \
          --artifact-registry ${{ env.ARTIFACT_REGISTRY }} \
          --model-path ${{ env.MODEL_PATH }}

    - name: Test Deployment
      run: |
        # Make test script executable
        chmod +x scripts/test_inference.py
        
        # Wait for service to be ready
        sleep 30
        
        # Run test script
        ./scripts/test_inference.py

    - name: Notify on Failure
      if: failure()
      run: |
        echo "Pipeline failed. Please check the logs for details."
        exit 1
